//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SealTest.SosiGW
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd")]
    public enum FaultCode
    {
        
        /// <remarks/>
        sosigw_no_valid_idcard_in_request,
        
        /// <remarks/>
        sosigw_missing_signinginfo_in_request,
        
        /// <remarks/>
        sosigw_syntax_error_in_request,
        
        /// <remarks/>
        sosigw_awaiting_signing,
        
        /// <remarks/>
        sosigw_no_valid_idcard_in_cache,
        
        /// <remarks/>
        sosigw_access_denied,
        
        /// <remarks/>
        sosigw_internal_error,
        
        /// <remarks/>
        sosigw_proxy_error,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sosi.dk/gw/2007.09.01", ConfigurationName="SealTest.SosiGW.SosiGWFacade")]
    public interface SosiGWFacade
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sosi.dk/gw/2007.09.01#requestIdCardDigestForSigning", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SealTest.SosiGW.FaultCode), Action="http://sosi.dk/gw/2007.09.01#requestIdCardDigestForSigning", Name="FaultCode", Namespace="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SealTest.SosiGW.requestIdCardDigestForSigningResponse1> requestIdCardDigestForSigningAsync(SealTest.SosiGW.requestIdCardDigestForSigningRequest request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://sosi.dk/gw/2007.09.01#logout")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task logoutAsync(SealTest.SosiGW.logoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sosi.dk/gw/2014.06.01#logoutWithResponse", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SealTest.SosiGW.FaultCode), Action="http://sosi.dk/gw/2014.06.01#logoutWithResponse", Name="FaultCode", Namespace="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SealTest.SosiGW.logoutResponse1> logoutWithResponseAsync(SealTest.SosiGW.logoutRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sosi.dk/gw/2007.09.01#getValidIdCard", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SealTest.SosiGW.FaultCode), Action="http://sosi.dk/gw/2007.09.01#getValidIdCard", Name="FaultCode", Namespace="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SealTest.SosiGW.getValidIdCardResponse> getValidIdCardAsync(SealTest.SosiGW.getValidIdCardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sosi.dk/gw/2007.09.01#signIdCard", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(SealTest.SosiGW.FaultCode), Action="http://sosi.dk/gw/2007.09.01#signIdCard", Name="FaultCode", Namespace="http://www.medcom.dk/dgws/2006/04/dgws-1.0.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<SealTest.SosiGW.signIdCardResponse1> signIdCardAsync(SealTest.SosiGW.signIdCardRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
        "")]
    public partial class Security
    {
        
        private Timestamp timestampField;
        
        private AssertionType assertionField;
        
        private Signature signatureField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xs" +
            "d", Order=0)]
        public Timestamp Timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:oasis:names:tc:SAML:2.0:assertion", Order=1)]
        public AssertionType Assertion
        {
            get
            {
                return this.assertionField;
            }
            set
            {
                this.assertionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", Order=2)]
        public Signature Signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xs" +
        "d")]
    public partial class Timestamp
    {
        
        private System.DateTime createdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime Created
        {
            get
            {
                return this.createdField;
            }
            set
            {
                this.createdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public partial class NameIDType
    {
        
        private SubjectIdentifierType formatField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SubjectIdentifierType Format
        {
            get
            {
                return this.formatField;
            }
            set
            {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public enum SubjectIdentifierType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:cprnumber")]
        medcomcprnumber,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:ynumber")]
        medcomynumber,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:pnumber")]
        medcompnumber,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:skscode")]
        medcomskscode,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:cvrnumber")]
        medcomcvrnumber,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:communalnumber")]
        medcomcommunalnumber,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:locationnumber")]
        medcomlocationnumber,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:itsystemname")]
        medcomitsystemname,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:other")]
        medcomother,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public partial class AssertionType
    {
        
        private string issuerField;
        
        private Subject subjectField;
        
        private Conditions conditionsField;
        
        private AttributeStatement[] attributeStatementField;
        
        private Signature signatureField;
        
        private System.DateTime issueInstantField;
        
        private decimal versionField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NCName", Order=0)]
        public string Issuer
        {
            get
            {
                return this.issuerField;
            }
            set
            {
                this.issuerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Subject Subject
        {
            get
            {
                return this.subjectField;
            }
            set
            {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Conditions Conditions
        {
            get
            {
                return this.conditionsField;
            }
            set
            {
                this.conditionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AttributeStatement", Order=3)]
        public AttributeStatement[] AttributeStatement
        {
            get
            {
                return this.attributeStatementField;
            }
            set
            {
                this.attributeStatementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", Order=4)]
        public Signature Signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime IssueInstant
        {
            get
            {
                return this.issueInstantField;
            }
            set
            {
                this.issueInstantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public partial class Subject
    {
        
        private NameIDType nameIDField;
        
        private SubjectConfirmation subjectConfirmationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NameIDType NameID
        {
            get
            {
                return this.nameIDField;
            }
            set
            {
                this.nameIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SubjectConfirmation SubjectConfirmation
        {
            get
            {
                return this.subjectConfirmationField;
            }
            set
            {
                this.subjectConfirmationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public partial class SubjectConfirmation
    {
        
        private ConfirmationMethod confirmationMethodField;
        
        private SubjectConfirmationData subjectConfirmationDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ConfirmationMethod ConfirmationMethod
        {
            get
            {
                return this.confirmationMethodField;
            }
            set
            {
                this.confirmationMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SubjectConfirmationData SubjectConfirmationData
        {
            get
            {
                return this.subjectConfirmationDataField;
            }
            set
            {
                this.subjectConfirmationDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public enum ConfirmationMethod
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("urn:oasis:names:tc:SAML:2.0:cm:holder-of-key")]
        urnoasisnamestcSAML20cmholderofkey,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public partial class SubjectConfirmationData
    {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UsernameToken", typeof(UsernameToken), Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
            "", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("KeyInfo", typeof(KeyInfo), Namespace="http://www.w3.org/2000/09/xmldsig#", Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
        "")]
    public partial class UsernameToken
    {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NCName", Order=0)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="NCName", Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class KeyInfo
    {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KeyName", typeof(string), DataType="NMTOKEN", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("X509Data", typeof(X509Data), Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class X509Data
    {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("KeyName", typeof(string), DataType="NMTOKEN", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("X509Certificate", typeof(byte[]), DataType="base64Binary", Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public partial class Conditions
    {
        
        private System.DateTime notBeforeField;
        
        private System.DateTime notOnOrAfterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime NotBefore
        {
            get
            {
                return this.notBeforeField;
            }
            set
            {
                this.notBeforeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime NotOnOrAfter
        {
            get
            {
                return this.notOnOrAfterField;
            }
            set
            {
                this.notOnOrAfterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public partial class AttributeStatement
    {
        
        private Attribute[] attributeField;
        
        private AttributeStatementID idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attribute", Order=0)]
        public Attribute[] Attribute
        {
            get
            {
                return this.attributeField;
            }
            set
            {
                this.attributeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AttributeStatementID id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public partial class Attribute
    {
        
        private string attributeValueField;
        
        private AttributeName nameField;
        
        private SubjectIdentifierType nameFormatField;
        
        private bool nameFormatFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AttributeValue
        {
            get
            {
                return this.attributeValueField;
            }
            set
            {
                this.attributeValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public AttributeName Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SubjectIdentifierType NameFormat
        {
            get
            {
                return this.nameFormatField;
            }
            set
            {
                this.nameFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NameFormatSpecified
        {
            get
            {
                return this.nameFormatFieldSpecified;
            }
            set
            {
                this.nameFormatFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public enum AttributeName
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sosi:IDCardID")]
        sosiIDCardID,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sosi:IDCardVersion")]
        sosiIDCardVersion,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sosi:IDCardType")]
        sosiIDCardType,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sosi:AuthenticationLevel")]
        sosiAuthenticationLevel,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("sosi:OCESCertHash")]
        sosiOCESCertHash,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:UserCivilRegistrationNumber")]
        medcomUserCivilRegistrationNumber,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:UserGivenName")]
        medcomUserGivenName,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:UserSurName")]
        medcomUserSurName,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:UserEmailAddress")]
        medcomUserEmailAddress,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:UserRole")]
        medcomUserRole,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:UserOccupation")]
        medcomUserOccupation,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:UserAuthorizationCode")]
        medcomUserAuthorizationCode,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:CareProviderID")]
        medcomCareProviderID,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:CareProviderName")]
        medcomCareProviderName,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("medcom:ITSystemName")]
        medcomITSystemName,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:oasis:names:tc:SAML:2.0:assertion")]
    public enum AttributeStatementID
    {
        
        /// <remarks/>
        IDCardData,
        
        /// <remarks/>
        UserLog,
        
        /// <remarks/>
        SystemLog,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class Signature
    {
        
        private SignedInfo signedInfoField;
        
        private byte[] signatureValueField;
        
        private KeyInfo keyInfoField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SignedInfo SignedInfo
        {
            get
            {
                return this.signedInfoField;
            }
            set
            {
                this.signedInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] SignatureValue
        {
            get
            {
                return this.signatureValueField;
            }
            set
            {
                this.signatureValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public KeyInfo KeyInfo
        {
            get
            {
                return this.keyInfoField;
            }
            set
            {
                this.keyInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignedInfo
    {
        
        private CanonicalizationMethod canonicalizationMethodField;
        
        private SignatureMethod signatureMethodField;
        
        private Reference[] referenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CanonicalizationMethod CanonicalizationMethod
        {
            get
            {
                return this.canonicalizationMethodField;
            }
            set
            {
                this.canonicalizationMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SignatureMethod SignatureMethod
        {
            get
            {
                return this.signatureMethodField;
            }
            set
            {
                this.signatureMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Reference", Order=2)]
        public Reference[] Reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class CanonicalizationMethod
    {
        
        private CanonicalizationMethodAlgorithm algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public CanonicalizationMethodAlgorithm Algorithm
        {
            get
            {
                return this.algorithmField;
            }
            set
            {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public enum CanonicalizationMethodAlgorithm
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/TR/2001/REC-xml-c14n-20010315")]
        httpwwww3orgTR2001RECxmlc14n20010315,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/2001/10/xml-exc-c14n#")]
        httpwwww3org200110xmlexcc14n,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignatureMethod
    {
        
        private SignatureMethodAlgorithm algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SignatureMethodAlgorithm Algorithm
        {
            get
            {
                return this.algorithmField;
            }
            set
            {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public enum SignatureMethodAlgorithm
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/2000/09/xmldsig#rsa-sha1")]
        httpwwww3org200009xmldsigrsasha1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class Reference
    {
        
        private Transforms transformsField;
        
        private DigestMethod digestMethodField;
        
        private byte[] digestValueField;
        
        private string uRIField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Transforms Transforms
        {
            get
            {
                return this.transformsField;
            }
            set
            {
                this.transformsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public DigestMethod DigestMethod
        {
            get
            {
                return this.digestMethodField;
            }
            set
            {
                this.digestMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] DigestValue
        {
            get
            {
                return this.digestValueField;
            }
            set
            {
                this.digestValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string URI
        {
            get
            {
                return this.uRIField;
            }
            set
            {
                this.uRIField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class Transforms
    {
        
        private TransformsTransform[] transformField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Transform", Order=0)]
        public TransformsTransform[] Transform
        {
            get
            {
                return this.transformField;
            }
            set
            {
                this.transformField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class TransformsTransform
    {
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Algorithm
        {
            get
            {
                return this.algorithmField;
            }
            set
            {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class DigestMethod
    {
        
        private DigestMethodAlgorithm algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DigestMethodAlgorithm Algorithm
        {
            get
            {
                return this.algorithmField;
            }
            set
            {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public enum DigestMethodAlgorithm
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/2000/09/xmldsig#rsa-sha1")]
        httpwwww3org200009xmldsigrsasha1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sosi.dk/gw/2007.09.01")]
    public partial class requestIdCardDigestForSigningResponse
    {
        
        private byte[] digestValueField;
        
        private string browserUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", DataType="base64Binary", Order=0)]
        public byte[] DigestValue
        {
            get
            {
                return this.digestValueField;
            }
            set
            {
                this.digestValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=1)]
        public string BrowserUrl
        {
            get
            {
                return this.browserUrlField;
            }
            set
            {
                this.browserUrlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class requestIdCardDigestForSigningRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
            "")]
        public SealTest.SosiGW.Security Security;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sosi.dk/gw/2007.09.01", Order=0)]
        public string requestIdCardDigestForSigningRequestBody;
        
        public requestIdCardDigestForSigningRequest()
        {
        }
        
        public requestIdCardDigestForSigningRequest(SealTest.SosiGW.Security Security, string requestIdCardDigestForSigningRequestBody)
        {
            this.Security = Security;
            this.requestIdCardDigestForSigningRequestBody = requestIdCardDigestForSigningRequestBody;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class requestIdCardDigestForSigningResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sosi.dk/gw/2007.09.01", Order=0)]
        public SealTest.SosiGW.requestIdCardDigestForSigningResponse requestIdCardDigestForSigningResponse;
        
        public requestIdCardDigestForSigningResponse1()
        {
        }
        
        public requestIdCardDigestForSigningResponse1(SealTest.SosiGW.requestIdCardDigestForSigningResponse requestIdCardDigestForSigningResponse)
        {
            this.requestIdCardDigestForSigningResponse = requestIdCardDigestForSigningResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logoutRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
            "")]
        public SealTest.SosiGW.Security Security;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sosi.dk/gw/2007.09.01", Order=0)]
        public string logoutRequestBody;
        
        public logoutRequest()
        {
        }
        
        public logoutRequest(SealTest.SosiGW.Security Security, string logoutRequestBody)
        {
            this.Security = Security;
            this.logoutRequestBody = logoutRequestBody;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sosi.dk/gw/2014.06.01")]
    public enum logoutResponse
    {
        
        /// <remarks/>
        ok,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logoutRequest1
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
            "")]
        public SealTest.SosiGW.Security Security;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sosi.dk/gw/2014.06.01", Order=0)]
        public string logoutRequestBody;
        
        public logoutRequest1()
        {
        }
        
        public logoutRequest1(SealTest.SosiGW.Security Security, string logoutRequestBody)
        {
            this.Security = Security;
            this.logoutRequestBody = logoutRequestBody;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logoutResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sosi.dk/gw/2014.06.01", Order=0)]
        public SealTest.SosiGW.logoutResponse logoutResponse;
        
        public logoutResponse1()
        {
        }
        
        public logoutResponse1(SealTest.SosiGW.logoutResponse logoutResponse)
        {
            this.logoutResponse = logoutResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getValidIdCardRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
            "")]
        public SealTest.SosiGW.Security Security;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sosi.dk/gw/2007.09.01", Order=0)]
        public string getValidIdCardRequestBody;
        
        public getValidIdCardRequest()
        {
        }
        
        public getValidIdCardRequest(SealTest.SosiGW.Security Security, string getValidIdCardRequestBody)
        {
            this.Security = Security;
            this.getValidIdCardRequestBody = getValidIdCardRequestBody;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getValidIdCardResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getValidIdCardResponse", Namespace="http://sosi.dk/gw/2007.09.01", Order=0)]
        public SealTest.SosiGW.AssertionType getValidIdCardResponse1;
        
        public getValidIdCardResponse()
        {
        }
        
        public getValidIdCardResponse(SealTest.SosiGW.AssertionType getValidIdCardResponse1)
        {
            this.getValidIdCardResponse1 = getValidIdCardResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sosi.dk/gw/2007.09.01")]
    public partial class signIdCardRequestBody
    {
        
        private byte[] signatureValueField;
        
        private KeyInfo keyInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", DataType="base64Binary", Order=0)]
        public byte[] SignatureValue
        {
            get
            {
                return this.signatureValueField;
            }
            set
            {
                this.signatureValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", Order=1)]
        public KeyInfo KeyInfo
        {
            get
            {
                return this.keyInfoField;
            }
            set
            {
                this.keyInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sosi.dk/gw/2007.09.01")]
    public enum signIdCardResponse
    {
        
        /// <remarks/>
        ok,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class signIdCardRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
            "")]
        public SealTest.SosiGW.Security Security;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sosi.dk/gw/2007.09.01", Order=0)]
        public SealTest.SosiGW.signIdCardRequestBody signIdCardRequestBody;
        
        public signIdCardRequest()
        {
        }
        
        public signIdCardRequest(SealTest.SosiGW.Security Security, SealTest.SosiGW.signIdCardRequestBody signIdCardRequestBody)
        {
            this.Security = Security;
            this.signIdCardRequestBody = signIdCardRequestBody;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class signIdCardResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sosi.dk/gw/2007.09.01", Order=0)]
        public SealTest.SosiGW.signIdCardResponse signIdCardResponse;
        
        public signIdCardResponse1()
        {
        }
        
        public signIdCardResponse1(SealTest.SosiGW.signIdCardResponse signIdCardResponse)
        {
            this.signIdCardResponse = signIdCardResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface SosiGWFacadeChannel : SealTest.SosiGW.SosiGWFacade, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class SosiGWFacadeClient : System.ServiceModel.ClientBase<SealTest.SosiGW.SosiGWFacade>, SealTest.SosiGW.SosiGWFacade
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SosiGWFacadeClient() : 
                base(SosiGWFacadeClient.GetDefaultBinding(), SosiGWFacadeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.SosiGWSoapBinding.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SosiGWFacadeClient(EndpointConfiguration endpointConfiguration) : 
                base(SosiGWFacadeClient.GetBindingForEndpoint(endpointConfiguration), SosiGWFacadeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SosiGWFacadeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SosiGWFacadeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SosiGWFacadeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SosiGWFacadeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SosiGWFacadeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SealTest.SosiGW.requestIdCardDigestForSigningResponse1> SealTest.SosiGW.SosiGWFacade.requestIdCardDigestForSigningAsync(SealTest.SosiGW.requestIdCardDigestForSigningRequest request)
        {
            return base.Channel.requestIdCardDigestForSigningAsync(request);
        }
        
        public System.Threading.Tasks.Task<SealTest.SosiGW.requestIdCardDigestForSigningResponse1> requestIdCardDigestForSigningAsync(SealTest.SosiGW.Security Security, string requestIdCardDigestForSigningRequestBody)
        {
            SealTest.SosiGW.requestIdCardDigestForSigningRequest inValue = new SealTest.SosiGW.requestIdCardDigestForSigningRequest();
            inValue.Security = Security;
            inValue.requestIdCardDigestForSigningRequestBody = requestIdCardDigestForSigningRequestBody;
            return ((SealTest.SosiGW.SosiGWFacade)(this)).requestIdCardDigestForSigningAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task SealTest.SosiGW.SosiGWFacade.logoutAsync(SealTest.SosiGW.logoutRequest request)
        {
            return base.Channel.logoutAsync(request);
        }
        
        public System.Threading.Tasks.Task logoutAsync(SealTest.SosiGW.Security Security, string logoutRequestBody)
        {
            SealTest.SosiGW.logoutRequest inValue = new SealTest.SosiGW.logoutRequest();
            inValue.Security = Security;
            inValue.logoutRequestBody = logoutRequestBody;
            return ((SealTest.SosiGW.SosiGWFacade)(this)).logoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SealTest.SosiGW.logoutResponse1> SealTest.SosiGW.SosiGWFacade.logoutWithResponseAsync(SealTest.SosiGW.logoutRequest1 request)
        {
            return base.Channel.logoutWithResponseAsync(request);
        }
        
        public System.Threading.Tasks.Task<SealTest.SosiGW.logoutResponse1> logoutWithResponseAsync(SealTest.SosiGW.Security Security, string logoutRequestBody)
        {
            SealTest.SosiGW.logoutRequest1 inValue = new SealTest.SosiGW.logoutRequest1();
            inValue.Security = Security;
            inValue.logoutRequestBody = logoutRequestBody;
            return ((SealTest.SosiGW.SosiGWFacade)(this)).logoutWithResponseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SealTest.SosiGW.getValidIdCardResponse> SealTest.SosiGW.SosiGWFacade.getValidIdCardAsync(SealTest.SosiGW.getValidIdCardRequest request)
        {
            return base.Channel.getValidIdCardAsync(request);
        }
        
        public System.Threading.Tasks.Task<SealTest.SosiGW.getValidIdCardResponse> getValidIdCardAsync(SealTest.SosiGW.Security Security, string getValidIdCardRequestBody)
        {
            SealTest.SosiGW.getValidIdCardRequest inValue = new SealTest.SosiGW.getValidIdCardRequest();
            inValue.Security = Security;
            inValue.getValidIdCardRequestBody = getValidIdCardRequestBody;
            return ((SealTest.SosiGW.SosiGWFacade)(this)).getValidIdCardAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SealTest.SosiGW.signIdCardResponse1> SealTest.SosiGW.SosiGWFacade.signIdCardAsync(SealTest.SosiGW.signIdCardRequest request)
        {
            return base.Channel.signIdCardAsync(request);
        }
        
        public System.Threading.Tasks.Task<SealTest.SosiGW.signIdCardResponse1> signIdCardAsync(SealTest.SosiGW.Security Security, SealTest.SosiGW.signIdCardRequestBody signIdCardRequestBody)
        {
            SealTest.SosiGW.signIdCardRequest inValue = new SealTest.SosiGW.signIdCardRequest();
            inValue.Security = Security;
            inValue.signIdCardRequestBody = signIdCardRequestBody;
            return ((SealTest.SosiGW.SosiGWFacade)(this)).signIdCardAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SosiGWSoapBinding))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SosiGWSoapBinding))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/sosigw/service/sosigw");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SosiGWFacadeClient.GetBindingForEndpoint(EndpointConfiguration.SosiGWSoapBinding);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SosiGWFacadeClient.GetEndpointAddress(EndpointConfiguration.SosiGWSoapBinding);
        }
        
        public enum EndpointConfiguration
        {
            
            SosiGWSoapBinding,
        }
    }
}
